### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by khurshedt9l** [bootsoon/ng-circle-progress#48]
i  getting below error
message: "Object(...) is not a function"
CircleProgressComponent/this.animate@webpack-internal:///./node_modules/ng-circle-progress/index.js:310:44\nCircleProgressComponent/this.render@webpack-internal:///./node_modules/ng-circle-progress/index.js:80:17\nCircleProgressComponent.prototype.ngOnChanges@webpack-internal

**Comment by bootsoon** [comment]
Version?

**Comment by khurshedt9l** [comment]
ng-circle-progress:1.0.0

**Comment by stefunices** [comment]
I'm facing same issue, please help

**Comment by bootsoon** [comment]
Could you paste some code or place it somewhere?

**Comment by stefunices** [comment]
events.module.ts
`import { NgModule } from '@angular/core';
import { ChartModule } from 'angular2-chartjs';
import { IonicPageModule } from 'ionic-angular';
import { ComponentsModule } from './../../components/components.module';
import { EventsPage } from './events';
import { ExamPipe } from './exam.pipe';
import { RoundProgressModule } from 'angular-svg-round-progressbar';
import { NgCircleProgressModule } from 'ng-circle-progress';

@NgModule({
  declarations: [
    EventsPage,
    ExamPipe,
  ],
  imports: [
    IonicPageModule.forChild(EventsPage),
    ComponentsModule,
    ChartModule,
    RoundProgressModule,
    NgCircleProgressModule.forRoot({
      radius: 100,
      outerStrokeWidth: 16,
      innerStrokeWidth: 8,
      outerStrokeColor: "#78C000",
      innerStrokeColor: "#C7E596",
      animationDuration: 300,
    })
  ],
})
export class EventsPageModule { }
`

events.html
` <circle-progress [percent]="85"></circle-progress>`

**Comment by stefunices** [comment]
Getting this Error: 

ERROR Error: "Uncaught (in promise): TypeError: Object(...) is not a function
CircleProgressComponent/this.animate@http://localhost:8100/build/0.js:34043:44
CircleProgressComponent/this.render@http://localhost:8100/build/0.js:33813:17
CircleProgressComponent.prototype.ngOnChanges@http://localhost:8100/build/0.js:34139:9

**Comment by tjadli** [comment]
Getting the same error on production !! 
ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at CircleProgressComponent.animate (index.js:302)
    at CircleProgressComponent.render (index.js:72)
    at CircleProgressComponent.webpackJsonp../node_modules/ng-circle-progress/index.js.CircleProgressComponent.ngOnChanges (index.js:398)
    at checkAndUpdateDirectiveInline (core.js:12092)

**Comment by noamyg** [comment]
I'm facing the same issue with the same version, I've disabled animation (`[animation]="false"`) as a workaround.

**Comment by tufafa** [comment]
Has anyone solved this problem？

**Comment by noamyg** [comment]
OK, I found it.
`CircleProgressComponent` uses `rjxs/timer` for animation, and has rxjs ^6.2.1 as a peerDependency. On version >6, import statements have been changed in rxjs. So if you have rxjs 5 as a module in your project, timer is not defined because it is declared like this in ng-circle-progress in its' new way:

`import { timer } from 'rxjs';`

The quick solution would be:

1. Update your rxjs dependency in your package.json, I manually changed it to `"rxjs": "^6.3.3",` and ran `npm install`
2. Now, all of your older import statements will become invalid. The real problem is that you might have some other dependencies that use the older declaration. The quick solution is shown [here](https://www.academind.com/learn/javascript/rxjs-6-what-changed/)  - just do `npm install rxjs-compat` so both of the statements work.

That should be it, `timer` is no longer undefined and everything else should work too.

@bootsoon IMHO rxjs-compact should be considered instead of rxjs to avoid this, I don't see any other usage of rxjs in here.
